services:
  apitfg:
    image: ${DOCKER_REGISTRY-}apitfg
    container_name: apiTFG
    ports:
     - "8080:8080"
     - "8081:8081"
    build:
      context: .
      dockerfile: ApiTFG/Dockerfile
    networks:
      - redTFG
  grok:
    image: ngrok/ngrok:latest
    container_name: ngrokApi
    command: http --url=native-supreme-locust.ngrok-free.app https://apitfg:8081
    environment:
      NGROK_AUTHTOKEN: 2x5Pts4Zr3ag79H70M7ZqEBvvXQ_46pE33sqKWzx3V537MDYm
    depends_on:
      - apitfg
    networks:
      - redTFG
# Esto todavia no funciona
  grok2:
    image: ngrok/ngrok:latest
    container_name: ngrokPagina
    command: http --url=commonly-crisp-hookworm.ngrok-free.app 5000
    environment:
      NGROK_AUTHTOKEN: 2xxg4gcH7UyGw2PRGtWQEuNnmgJ_2ZTXyWk7G3rMNNCRxWehC
networks:
  redTFG:
    external: true  
   