services:
  apitfg:
    image: ${DOCKER_REGISTRY-}apitfg
    container_name: apiTFG
    ports:
     - "8080:8080"
     - "8081:8081"
    build:
      context: .
      dockerfile: ApiTFG/Dockerfile
    networks:
      - redTFG
  # grok:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrokApi
  #   command: http --url=native-supreme-locust.ngrok-free.app https://apitfg:8081
  #   environment:
  #     NGROK_AUTHTOKEN: 2x5Pts4Zr3ag79H70M7ZqEBvvXQ_46pE33sqKWzx3V537MDYm
  #   depends_on:
  #     - apitfg
  #   networks:
  #     - redTFG
  # pagina:
  #   container_name: paginaTFG
  #   ports:
  #    - "5001:5001"
  #   build:
  #     context: .
  #     dockerfile: pagina/Dockerfile
  #   networks:
  #     - redTFG
  # grok2:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrokPagina
  #   command: http --url=commonly-crisp-hookworm.ngrok-free.app http://pagina:5001
  #   depends_on:
  #     - pagina
  #   environment:
  #     NGROK_AUTHTOKEN: 2xxg4gcH7UyGw2PRGtWQEuNnmgJ_2ZTXyWk7G3rMNNCRxWehC
  #   networks:
  #     - redTFG
  # influxdb:
  #   image: influxdb:1.8
  #   container_name: influxdb
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - INFLUXDB_DB=k6db
  #   volumes:
  #     - influxdb_data:/var/lib/influxdb
  #   networks:
  #     - redTFG
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - influxdb
  #   networks:
  #     - redTFG
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  # k6:
  #   image: loadimpact/k6:latest
  #   container_name: k6
  #   depends_on:
  #     - influxdb
  #   networks:
  #     - redTFG
  #   volumes:
  #     - ./Tests/stress-test.js:/scripts/stress-test.js:ro
  #   entrypoint: ["k6"]
  #   command: ["run","--insecure-skip-tls-verify", "--out", "influxdb=http://influxdb:8086/k6db", "/scripts/stress-test.js"]

networks:
  redTFG:
    external: true  
volumes:
  influxdb_data: {}
  grafana_data: {}